### ISSUE TITLE
Not found Framework "Pods-Shared-ActivitiSDK-frameworks.sh"

### ISSUE THREAD

**Issue by KaneNguyen** [Alfresco/activiti-ios#275] opened 2017-05-25 03:25 UTC
Dear Team, 
After pod install and build app xcode show fail with description :"/Users/xxxxx/Library/Developer/Xcode/DerivedData/AlfrescoActiviti-bqzsgffrewsvrcfdtxhsxhkcddso/Build/Intermediates/AlfrescoActiviti.build/Debug-iphonesimulator/ActivitiSDK.build/Script-7597AEF01B82580800F8B5DE.sh: line 2: /Users/xxxxx/Desktop/activiti-ios-master/Pods/Target Support Files/Pods-Shared-ActivitiSDK/Pods-Shared-ActivitiSDK-frameworks.sh: No such file or directory".
Please help me,
Thank you,

**Comment by emanuellupu** [comment] 2017-05-25 07:19
Hi @KaneNguyen, thanks for reporting, I'll look into it and follow up.

**Comment by emanuellupu** [comment] 2017-05-25 14:31
@KaneNguyen Could you provide some additional information like the Cocoapods version that you have locally? How about XCode version? Have you tried it with a specific release tag or the latest on master?

For now, I suggest you should try again to build the project without running the `pod install` command because the pods are already added to the repository. Let me know how that works and I'll further assist you from there.

**Comment by KaneNguyen** [comment] 2017-05-26 01:21
@emanuellupu  Cocoapods version: 2.6.11, Xcode version: 8.3, i tried with master version.
Now, I tried build project without the pod install and result "success". So why fail when i build with pod install. how make when i want add new frameworks ?
Thank @emanuellupu,

**Comment by emanuellupu** [comment] 2017-05-26 11:19
I've managed to reproduce your issue on my side and this is happening mainly because of how Cocoapods works. I'll refer you to the full discussion on the raised issue: https://github.com/CocoaPods/CocoaPods/issues/4203 . 

The issue that you are encountering is due to a build phase script that is executed as a workaround for Appstore validation rejection. To put it simple, if you'll not execute this workaround that removes a reminiscence of the Cocoapods linkage process Apple will reject your binary when you'll try to submit it for review because a nested Frameworks folder structure will be present in the .app . You can read more about it on the issue that I've referenced above. 

So for now, if you want to add additional pods you just need to disable that script before running the `pod install` and enable it before submitting to Apple. To do that you need to go to select the `ActivitiSDK` target, go to `Build Phases` and disable the `Cocoapods framework clean script`. 

Hope that clears things a little bit more. I'll be searching in the meantime for a more robust solution and reference this issue if I commit changes for it so that you'll be updated. 

Let me know if that works for you.

**Comment by KaneNguyen** [comment] 2017-05-29 01:11
I got it,
Thank you @emanuellupu

**Comment by emanuellupu** [comment] 2017-05-29 07:41
Leaving the ticket open for tracking purposes.

**Comment by emanuellupu** [comment] 2020-02-11 11:26
Closing the issue as this should be solved now. Feel free to reopen if you encounter the issue again.

**Closed by emanuellupu** 2020-02-11 11:26 UTC
Labels: enhancement
